In [128]:
import pandas as pd
import numpy as np

In [129]:
df = pd.read_csv('../data/raw_data/cc-est2017-alldata.csv', encoding = "ISO-8859-1")  #Age, sex, gender
# Each year, the United States Census Bureau produces and publishes estimates of the population for the nation,
# states, counties, state/county equivalents, and Puerto Rico

In [130]:
#TO MAKE A FIPS FILE WITH COUNT NAMES, EXPORTED THE FOLLOWING

# unique_cty_states = df[['CTYNAME', 'STNAME']].copy()
# unique_cty_states = unique_cty_states.drop_duplicates()
# unique_cty_states.to_csv('../data/Census-County-names')

In [131]:
df.index

RangeIndex(start=0, stop=596980, step=1)

In [181]:
df[df['CTYNAME'].str.contains('alawao')]

,SUMLEV,STATE,COUNTY,STNAME,CTYNAME,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,...,HWAC_FEMALE,HBAC_MALE,HBAC_FEMALE,HIAC_MALE,HIAC_FEMALE,HAAC_MALE,HAAC_FEMALE,HNAC_MALE,HNAC_FEMALE,StateCounty
104120,50,15,5,Hawaii,Kalawao County,1,0,90,42,48,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104121,50,15,5,Hawaii,Kalawao County,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104122,50,15,5,Hawaii,Kalawao County,1,2,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104123,50,15,5,Hawaii,Kalawao County,1,3,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104124,50,15,5,Hawaii,Kalawao County,1,4,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104125,50,15,5,Hawaii,Kalawao County,1,5,3,1,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104126,50,15,5,Hawaii,Kalawao County,1,6,4,2,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104127,50,15,5,Hawaii,Kalawao County,1,7,6,3,3,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104128,50,15,5,Hawaii,Kalawao County,1,8,6,3,3,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104129,50,15,5,Hawaii,Kalawao County,1,9,8,6,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104130,50,15,5,Hawaii,Kalawao County,1,10,8,6,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104131,50,15,5,Hawaii,Kalawao County,1,11,9,6,3,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104132,50,15,5,Hawaii,Kalawao County,1,12,17,11,6,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104133,50,15,5,Hawaii,Kalawao County,1,13,3,0,3,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104134,50,15,5,Hawaii,Kalawao County,1,14,2,1,1,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104135,50,15,5,Hawaii,Kalawao County,1,15,5,0,5,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104136,50,15,5,Hawaii,Kalawao County,1,16,9,0,9,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104137,50,15,5,Hawaii,Kalawao County,1,17,9,2,7,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104138,50,15,5,Hawaii,Kalawao County,1,18,1,1,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104139,50,15,5,Hawaii,Kalawao County,2,0,90,42,48,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104140,50,15,5,Hawaii,Kalawao County,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104141,50,15,5,Hawaii,Kalawao County,2,2,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104142,50,15,5,Hawaii,Kalawao County,2,3,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104143,50,15,5,Hawaii,Kalawao County,2,4,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104144,50,15,5,Hawaii,Kalawao County,2,5,3,1,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104145,50,15,5,Hawaii,Kalawao County,2,6,4,2,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104146,50,15,5,Hawaii,Kalawao County,2,7,6,3,3,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104147,50,15,5,Hawaii,Kalawao County,2,8,6,3,3,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104148,50,15,5,Hawaii,Kalawao County,2,9,8,6,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104149,50,15,5,Hawaii,Kalawao County,2,10,8,6,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104280,50,15,5,Hawaii,Kalawao County,9,8,4,2,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104281,50,15,5,Hawaii,Kalawao County,9,9,5,3,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104282,50,15,5,Hawaii,Kalawao County,9,10,6,2,4,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104283,50,15,5,Hawaii,Kalawao County,9,11,13,10,3,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104284,50,15,5,Hawaii,Kalawao County,9,12,5,2,3,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104285,50,15,5,Hawaii,Kalawao County,9,13,16,11,5,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104286,50,15,5,Hawaii,Kalawao County,9,14,7,4,3,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104287,50,15,5,Hawaii,Kalawao County,9,15,3,1,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104288,50,15,5,Hawaii,Kalawao County,9,16,5,0,5,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104289,50,15,5,Hawaii,Kalawao County,9,17,5,0,5,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104290,50,15,5,Hawaii,Kalawao County,9,18,12,3,9,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104291,50,15,5,Hawaii,Kalawao County,10,0,88,42,46,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104292,50,15,5,Hawaii,Kalawao County,10,1,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104293,50,15,5,Hawaii,Kalawao County,10,2,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104294,50,15,5,Hawaii,Kalawao County,10,3,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104295,50,15,5,Hawaii,Kalawao County,10,4,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104296,50,15,5,Hawaii,Kalawao County,10,5,0,0,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104297,50,15,5,Hawaii,Kalawao County,10,6,1,1,0,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104298,50,15,5,Hawaii,Kalawao County,10,7,6,3,3,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104299,50,15,5,Hawaii,Kalawao County,10,8,4,2,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104300,50,15,5,Hawaii,Kalawao County,10,9,3,1,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104301,50,15,5,Hawaii,Kalawao County,10,10,6,3,3,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104302,50,15,5,Hawaii,Kalawao County,10,11,13,9,4,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104303,50,15,5,Hawaii,Kalawao County,10,12,7,4,3,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104304,50,15,5,Hawaii,Kalawao County,10,13,14,10,4,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104305,50,15,5,Hawaii,Kalawao County,10,14,9,5,4,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104306,50,15,5,Hawaii,Kalawao County,10,15,2,0,2,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104307,50,15,5,Hawaii,Kalawao County,10,16,5,1,4,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104308,50,15,5,Hawaii,Kalawao County,10,17,6,0,6,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County
104309,50,15,5,Hawaii,Kalawao County,10,18,12,3,9,...,0,0,0,0,0,0,0,0,0,HawaiiKalawao County

In [180]:
df.loc[554408]["CTYNAME"]

'Buena Vista city'

In [182]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 596980 entries, 0 to 596979
Data columns (total 81 columns):
SUMLEV          596980 non-null int64
STATE           596980 non-null int64
COUNTY          596980 non-null int64
STNAME          596980 non-null object
CTYNAME         596980 non-null object
YEAR            596980 non-null int64
AGEGRP          596980 non-null int64
TOT_POP         596980 non-null int64
TOT_MALE        596980 non-null int64
TOT_FEMALE      596980 non-null int64
WA_MALE         596980 non-null int64
WA_FEMALE       596980 non-null int64
BA_MALE         596980 non-null int64
BA_FEMALE       596980 non-null int64
IA_MALE         596980 non-null int64
IA_FEMALE       596980 non-null int64
AA_MALE         596980 non-null int64
AA_FEMALE       596980 non-null int64
NA_MALE         596980 non-null int64
NA_FEMALE       596980 non-null int64
TOM_MALE        596980 non-null int64
TOM_FEMALE      596980 non-null int64
WAC_MALE        596980 non-null int64
WAC_FEMALE      596980 non-null int64
BAC_MALE        596980 non-null int64
BAC_FEMALE      596980 non-null int64
IAC_MALE        596980 non-null int64
IAC_FEMALE      596980 non-null int64
AAC_MALE        596980 non-null int64
AAC_FEMALE      596980 non-null int64
NAC_MALE        596980 non-null int64
NAC_FEMALE      596980 non-null int64
NH_MALE         596980 non-null int64
NH_FEMALE       596980 non-null int64
NHWA_MALE       596980 non-null int64
NHWA_FEMALE     596980 non-null int64
NHBA_MALE       596980 non-null int64
NHBA_FEMALE     596980 non-null int64
NHIA_MALE       596980 non-null int64
NHIA_FEMALE     596980 non-null int64
NHAA_MALE       596980 non-null int64
NHAA_FEMALE     596980 non-null int64
NHNA_MALE       596980 non-null int64
NHNA_FEMALE     596980 non-null int64
NHTOM_MALE      596980 non-null int64
NHTOM_FEMALE    596980 non-null int64
NHWAC_MALE      596980 non-null int64
NHWAC_FEMALE    596980 non-null int64
NHBAC_MALE      596980 non-null int64
NHBAC_FEMALE    596980 non-null int64
NHIAC_MALE      596980 non-null int64
NHIAC_FEMALE    596980 non-null int64
NHAAC_MALE      596980 non-null int64
NHAAC_FEMALE    596980 non-null int64
NHNAC_MALE      596980 non-null int64
NHNAC_FEMALE    596980 non-null int64
H_MALE          596980 non-null int64
H_FEMALE        596980 non-null int64
HWA_MALE        596980 non-null int64
HWA_FEMALE      596980 non-null int64
HBA_MALE        596980 non-null int64
HBA_FEMALE      596980 non-null int64
HIA_MALE        596980 non-null int64
HIA_FEMALE      596980 non-null int64
HAA_MALE        596980 non-null int64
HAA_FEMALE      596980 non-null int64
HNA_MALE        596980 non-null int64
HNA_FEMALE      596980 non-null int64
HTOM_MALE       596980 non-null int64
HTOM_FEMALE     596980 non-null int64
HWAC_MALE       596980 non-null int64
HWAC_FEMALE     596980 non-null int64
HBAC_MALE       596980 non-null int64
HBAC_FEMALE     596980 non-null int64
HIAC_MALE       596980 non-null int64
HIAC_FEMALE     596980 non-null int64
HAAC_MALE       596980 non-null int64
HAAC_FEMALE     596980 non-null int64
HNAC_MALE       596980 non-null int64
HNAC_FEMALE     596980 non-null int64
StateCounty     596980 non-null object
dtypes: int64(78), object(3)
memory usage: 368.9+ MB

In [183]:
#Add FIPS columns

In [184]:
fips = pd.read_csv('../data/county_fips_mapping.csv')

In [185]:
fips.head()

   Unnamed: 0  fips   county state_abbr    state  census_CTYNAME
0           0  1001  Autauga         AL  Alabama  Autauga County
1           1  1003  Baldwin         AL  Alabama  Baldwin County
2           2  1005  Barbour         AL  Alabama  Barbour County
3           3  1007     Bibb         AL  Alabama     Bibb County
4           4  1009   Blount         AL  Alabama   Blount County

In [186]:
fips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3236 entries, 0 to 3235
Data columns (total 6 columns):
Unnamed: 0        3236 non-null int64
fips              3236 non-null int64
county            3236 non-null object
state_abbr        3236 non-null object
state             3236 non-null object
census_CTYNAME    3236 non-null object
dtypes: int64(2), object(4)
memory usage: 151.8+ KB

In [187]:
fips['StateCounty'] = fips['state'] + fips['census_CTYNAME']
df['StateCounty'] = df["STNAME"] + df["CTYNAME"]
df.shape

(596980, 81)

In [188]:
newdf = df.merge(fips[['StateCounty', "fips", "state", "county", 'census_CTYNAME']], on = "StateCounty", how = 'left')
newdf.head()

,SUMLEV,STATE,COUNTY,STNAME,CTYNAME,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,...,HIAC_FEMALE,HAAC_MALE,HAAC_FEMALE,HNAC_MALE,HNAC_FEMALE,StateCounty,fips,state,county,census_CTYNAME
0,50,1,1,Alabama,Autauga County,1,0,54571,26569,28002,...,32,9,11,19,10,AlabamaAutauga County,1001.0,Alabama,Autauga,Autauga County
1,50,1,1,Alabama,Autauga County,1,1,3579,1866,1713,...,1,0,0,2,1,AlabamaAutauga County,1001.0,Alabama,Autauga,Autauga County
2,50,1,1,Alabama,Autauga County,1,2,3991,2001,1990,...,7,2,3,2,0,AlabamaAutauga County,1001.0,Alabama,Autauga,Autauga County
3,50,1,1,Alabama,Autauga County,1,3,4290,2171,2119,...,5,2,1,1,1,AlabamaAutauga County,1001.0,Alabama,Autauga,Autauga County
4,50,1,1,Alabama,Autauga County,1,4,4290,2213,2077,...,2,2,1,3,1,AlabamaAutauga County,1001.0,Alabama,Autauga,Autauga County

In [189]:
newdf.shape

(596980, 85)

In [190]:
## Only taking Year = 1

In [191]:
starter_demos = newdf[['STNAME', 'CTYNAME', "fips", "YEAR", "AGEGRP", "TOT_POP", "TOT_MALE", "TOT_FEMALE"]]

In [192]:
starter_demos["pct_male"] =  starter_demos["TOT_MALE"] / starter_demos["TOT_POP"]

/Users/LB/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [193]:
first_pass = starter_demos[starter_demos["YEAR"] == 1]   #Year 1 is 2010, data from the original sensus
first_pass.head()

,STNAME,CTYNAME,fips,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,pct_male
0,Alabama,Autauga County,1001.0,1,0,54571,26569,28002,0.486870
1,Alabama,Autauga County,1001.0,1,1,3579,1866,1713,0.521375
2,Alabama,Autauga County,1001.0,1,2,3991,2001,1990,0.501378
3,Alabama,Autauga County,1001.0,1,3,4290,2171,2119,0.506061
4,Alabama,Autauga County,1001.0,1,4,4290,2213,2077,0.515851

In [194]:
first_pass[first_pass['CTYNAME'] == "Adams County"]
#Adair County

first_pass[first_pass['CTYNAME'] == "Adams County"]['fips'].unique()

array([ 8001., 16003., 17001., 18001., 19003., 28001., 31001., 38001.,
       39001., 42001., 53001., 55001.])

In [195]:
# The key for AGEGRP is as follows:
# 0 = Total
# 1 = Age 0 to 4 years
# 2 = Age 5 to 9 years
# 3 = Age 10 to 14 years
# 4 = Age 15 to 19 years
# 5 = Age 20 to 24 years
# 6 = Age 25 to 29 years
# 7 = Age 30 to 34 years
# 8 = Age 35 to 39 years
# 9 = Age 40 to 44 years
# 10 = Age 45 to 49 years
# 11 = Age 50 to 54 years
# 12 = Age 55 to 59 years
# 13 = Age 60 to 64 years
# 14 = Age 65 to 69 years
# 15 = Age 70 to 74 years
# 16 = Age 75 to 79 years
# 17 = Age 80 to 84 years
# 18 = Age 85 years or older

In [196]:
#Double checking: does it all add up for 2010?

In [197]:
ages_total = first_pass[first_pass["AGEGRP"] != 0]
ages_total = ages_total.groupby("fips").sum()["TOT_POP"]

In [198]:
ages_total = ages_total.reset_index()
ages_total.head(7)

     fips  TOT_POP
0  1001.0    54571
1  1003.0   182265
2  1005.0    27457
3  1007.0    22915
4  1009.0    57322
5  1011.0    10914
6  1013.0    20947

In [199]:
ages_total_given = first_pass[first_pass["AGEGRP"] == 0][['fips','TOT_POP']]

In [200]:
ages_total_given = ages_total_given.sort_values(by=['fips']).reset_index()
ages_total_given.head(7)

   index    fips  TOT_POP
0      0  1001.0    54571
1    190  1003.0   182265
2    380  1005.0    27457
3    570  1007.0    22915
4    760  1009.0    57322
5    950  1011.0    10914
6   1140  1013.0    20947

In [201]:
print(ages_total.shape)
print(ages_total_given.shape)

(3141, 2)
(3142, 3)

In [202]:
##  doesn't matter
##(ages_total['TOT_POP'] == ages_total_given['TOT_POP']).sum()

In [203]:
#confirmed! Ages are exhaustive

In [162]:
#Back to making age group columns

In [163]:
Age_Mapping = {
    1: "2010:AgeGroup01:0-4",
    2: "2010:AgeGroup02:5-9",
    3: "2010:AgeGroup03:10-14",
    4: "2010:AgeGroup04:15-19",
    5: "2010:AgeGroup05:20-24",
    6: "2010:AgeGroup06:25-29",
    7: "2010:AgeGroup07:30-34",
    8: "2010:AgeGroup08:35-39",
    9: "2010:AgeGroup09:40-44",
    10: "2010:AgeGroup10:45-49",
    11: "2010:AgeGroup11:50-54",
    12: "2010:AgeGroup12:55-59",
    13: "2010:AgeGroup13:60-64",
    14: "2010:AgeGroup14:65-69",
    15: "2010:AgeGroup15:70-74",
    16: "2010:AgeGroup16:75-79",
    17: "2010:AgeGroup17:80-84",
    18: "2010:AgeGroup18:85+",
}

In [164]:
first_pass.head()

,STNAME,CTYNAME,fips,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,pct_male
0,Alabama,Autauga County,1001.0,1,0,54571,26569,28002,0.486870
1,Alabama,Autauga County,1001.0,1,1,3579,1866,1713,0.521375
2,Alabama,Autauga County,1001.0,1,2,3991,2001,1990,0.501378
3,Alabama,Autauga County,1001.0,1,3,4290,2171,2119,0.506061
4,Alabama,Autauga County,1001.0,1,4,4290,2213,2077,0.515851

In [165]:
first_pass_age_totals = first_pass[first_pass["AGEGRP"] == 0][["STNAME", "CTYNAME", "fips", "AGEGRP", "TOT_POP", "pct_male" ]].sort_values(by=['fips'])
first_pass_age_totals.head()

      STNAME         CTYNAME    fips  AGEGRP  TOT_POP  pct_male
0    Alabama  Autauga County  1001.0       0    54571  0.486870
190  Alabama  Baldwin County  1003.0       0   182265  0.489375
380  Alabama  Barbour County  1005.0       0    27457  0.530866
570  Alabama     Bibb County  1007.0       0    22915  0.536810
760  Alabama   Blount County  1009.0       0    57322  0.494784

In [166]:
for i in range(1, 19):
    agegrp = first_pass[first_pass["AGEGRP"] == i][["fips", "AGEGRP", "TOT_POP" ]].sort_values(by=['fips'])
    print(agegrp.head())
    first_pass_final[Age_Mapping[i]] = np.array(agegrp["TOT_POP"]) / np.array(first_pass_age_totals["TOT_POP"])
    print(first_pass_final[Age_Mapping[i]].head())

       fips  AGEGRP  TOT_POP
1    1001.0       1     3579
191  1003.0       1    11158
381  1005.0       1     1702
571  1007.0       1     1378
761  1009.0       1     3616
0      0.065584
190    0.061219
380    0.061988
570    0.060135
760    0.063082
Name: 2010:AgeGroup01:0-4, dtype: float64
       fips  AGEGRP  TOT_POP
2    1001.0       2     3991
192  1003.0       2    11599
382  1005.0       2     1642
572  1007.0       2     1405
762  1009.0       2     3880
0      0.073134
190    0.063638
380    0.059803
570    0.061314
760    0.067688
Name: 2010:AgeGroup02:5-9, dtype: float64
       fips  AGEGRP  TOT_POP
3    1001.0       3     4290
193  1003.0       3    11926
383  1005.0       3     1599
573  1007.0       3     1440
763  1009.0       3     4084
0      0.078613
190    0.065432
380    0.058237
570    0.062841
760    0.071247
Name: 2010:AgeGroup03:10-14, dtype: float64
       fips  AGEGRP  TOT_POP
4    1001.0       4     4290
194  1003.0       4    11600
384  1005.0       4     1731
574  1007.0       4     1543
764  1009.0       4     4033
0      0.078613
190    0.063644
380    0.063044
570    0.067336
760    0.070357
Name: 2010:AgeGroup04:15-19, dtype: float64
       fips  AGEGRP  TOT_POP
5    1001.0       5     3080
195  1003.0       5     9449
385  1005.0       5     1794
575  1007.0       5     1491
765  1009.0       5     3107
0      0.056440
190    0.051842
380    0.065339
570    0.065067
760    0.054203
Name: 2010:AgeGroup05:20-24, dtype: float64
       fips  AGEGRP  TOT_POP
6    1001.0       6     3157
196  1003.0       6    10247
386  1005.0       6     2010
576  1007.0       6     1603
766  1009.0       6     3436
0      0.057851
190    0.056220
380    0.073205
570    0.069954
760    0.059942
Name: 2010:AgeGroup06:25-29, dtype: float64
       fips  AGEGRP  TOT_POP
7    1001.0       7     3330
197  1003.0       7    10709
387  1005.0       7     1808
577  1007.0       7     1646
767  1009.0       7     3441
0      0.061021
190    0.058755
380    0.065848
570    0.071831
760    0.060029
Name: 2010:AgeGroup07:30-34, dtype: float64
       fips  AGEGRP  TOT_POP
8    1001.0       8     4157
198  1003.0       8    11558
388  1005.0       8     1819
578  1007.0       8     1747
768  1009.0       8     3892
0      0.076176
190    0.063413
380    0.066249
570    0.076238
760    0.067897
Name: 2010:AgeGroup08:35-39, dtype: float64
       fips  AGEGRP  TOT_POP
9    1001.0       9     4086
199  1003.0       9    11995
389  1005.0       9     1809
579  1007.0       9     1635
769  1009.0       9     4033
0      0.074875
190    0.065811
380    0.065885
570    0.071351
760    0.070357
Name: 2010:AgeGroup09:40-44, dtype: float64
       fips  AGEGRP  TOT_POP
10   1001.0      10     4332
200  1003.0      10    13431
390  1005.0      10     2108
580  1007.0      10     1805
770  1009.0      10     4163
0      0.079383
190    0.073689
380    0.076775
570    0.078769
760    0.072625
Name: 2010:AgeGroup10:45-49, dtype: float64
       fips  AGEGRP  TOT_POP
11   1001.0      11     3873
201  1003.0      11    13490
391  1005.0      11     1910
581  1007.0      11     1581
771  1009.0      11     3922
0      0.070972
190    0.074013
380    0.069563
570    0.068994
760    0.068421
Name: 2010:AgeGroup11:50-54, dtype: float64
       fips  AGEGRP  TOT_POP
12   1001.0      12     3083
202  1003.0      12    12523
392  1005.0      12     1817
582  1007.0      12     1401
772  1009.0      12     3694
0      0.056495
190    0.068708
380    0.066176
570    0.061139
760    0.064443
Name: 2010:AgeGroup12:55-59, dtype: float64
       fips  AGEGRP  TOT_POP
13   1001.0      13     2777
203  1003.0      13    12012
393  1005.0      13     1799
583  1007.0      13     1334
773  1009.0      13     3582
0      0.050888
190    0.065904
380    0.065521
570    0.058215
760    0.062489
Name: 2010:AgeGroup13:60-64, dtype: float64
       fips  AGEGRP  TOT_POP
14   1001.0      14     2277
204  1003.0      14    10174
394  1005.0      14     1290
584  1007.0      14      966
774  1009.0      14     2892
0      0.041725
190    0.055820
380    0.046983
570    0.042156
760    0.050452
Name: 2010:AgeGroup14:65-69, dtype: float64
       fips  AGEGRP  TOT_POP
15   1001.0      15     1736
205  1003.0      15     7629
395  1005.0      15      948
585  1007.0      15      757
775  1009.0      15     2187
0      0.031812
190    0.041857
380    0.034527
570    0.033035
760    0.038153
Name: 2010:AgeGroup15:70-74, dtype: float64
       fips  AGEGRP  TOT_POP
16   1001.0      16     1251
206  1003.0      16     5598
396  1005.0      16      685
586  1007.0      16      549
776  1009.0      16     1517
0      0.022924
190    0.030714
380    0.024948
570    0.023958
760    0.026465
Name: 2010:AgeGroup16:75-79, dtype: float64
       fips  AGEGRP  TOT_POP
17   1001.0      17      731
207  1003.0      17     3934
397  1005.0      17      543
587  1007.0      17      355
777  1009.0      17     1035
0      0.013395
190    0.021584
380    0.019776
570    0.015492
760    0.018056
Name: 2010:AgeGroup17:80-84, dtype: float64
       fips  AGEGRP  TOT_POP
18   1001.0      18      551
208  1003.0      18     3233
398  1005.0      18      443
588  1007.0      18      279
778  1009.0      18      808
0      0.010097
190    0.017738
380    0.016134
570    0.012175
760    0.014096
Name: 2010:AgeGroup18:85+, dtype: float64

In [167]:
# agegrp1 = first_pass[first_pass["AGEGRP"] == 1][["fips", "AGEGRP", "TOT_POP" ]].sort_values(by=['fips'])
# agegrp1.head()
# pop_all_ages[Age_Mapping[1]] = np.array(agegrp1["TOT_POP"]) / np.array(pop_all_ages["TOT_POP"])

In [168]:
first_pass_final.head()

,STNAME,CTYNAME,fips,AGEGRP,TOT_POP,pct_male,2010:AgeGroup01:0-4,2010:AgeGroup02:5-9,2010:AgeGroup03:10-14,2010:AgeGroup04:15-19,...,2010:AgeGroup09:40-44,2010:AgeGroup10:45-49,2010:AgeGroup11:50-54,2010:AgeGroup12:55-59,2010:AgeGroup13:60-64,2010:AgeGroup14:65-69,2010:AgeGroup15:70-74,2010:AgeGroup16:75-79,2010:AgeGroup17:80-84,2010:AgeGroup18:85+
0,Alabama,Autauga County,1001,0,54571,0.486870,0.065584,0.073134,0.078613,0.078613,...,0.074875,0.079383,0.070972,0.056495,0.050888,0.041725,0.031812,0.022924,0.013395,0.010097
190,Alabama,Baldwin County,1003,0,182265,0.489375,0.061219,0.063638,0.065432,0.063644,...,0.065811,0.073689,0.074013,0.068708,0.065904,0.055820,0.041857,0.030714,0.021584,0.017738
380,Alabama,Barbour County,1005,0,27457,0.530866,0.061988,0.059803,0.058237,0.063044,...,0.065885,0.076775,0.069563,0.066176,0.065521,0.046983,0.034527,0.024948,0.019776,0.016134
570,Alabama,Bibb County,1007,0,22915,0.536810,0.060135,0.061314,0.062841,0.067336,...,0.071351,0.078769,0.068994,0.061139,0.058215,0.042156,0.033035,0.023958,0.015492,0.012175
760,Alabama,Blount County,1009,0,57322,0.494784,0.063082,0.067688,0.071247,0.070357,...,0.070357,0.072625,0.068421,0.064443,0.062489,0.050452,0.038153,0.026465,0.018056,0.014096

In [169]:
#check to make sure ages sum to zero
first_pass_final[['2010:AgeGroup01:0-4', '2010:AgeGroup02:5-9', '2010:AgeGroup03:10-14',
       '2010:AgeGroup04:15-19', '2010:AgeGroup05:20-24',
       '2010:AgeGroup06:25-29', '2010:AgeGroup07:30-34',
       '2010:AgeGroup08:35-39', '2010:AgeGroup09:40-44',
       '2010:AgeGroup10:45-49', '2010:AgeGroup11:50-54',
       '2010:AgeGroup12:55-59', '2010:AgeGroup13:60-64',
       '2010:AgeGroup14:65-69', '2010:AgeGroup15:70-74',
       '2010:AgeGroup16:75-79', '2010:AgeGroup17:80-84',
       '2010:AgeGroup18:85+']].sum(axis = 1)[:5]

0      1.0
190    1.0
380    1.0
570    1.0
760    1.0
dtype: float64

In [170]:
first_pass_final.columns

Index(['STNAME', 'CTYNAME', 'fips', 'AGEGRP', 'TOT_POP', 'pct_male',
       '2010:AgeGroup01:0-4', '2010:AgeGroup02:5-9', '2010:AgeGroup03:10-14',
       '2010:AgeGroup04:15-19', '2010:AgeGroup05:20-24',
       '2010:AgeGroup06:25-29', '2010:AgeGroup07:30-34',
       '2010:AgeGroup08:35-39', '2010:AgeGroup09:40-44',
       '2010:AgeGroup10:45-49', '2010:AgeGroup11:50-54',
       '2010:AgeGroup12:55-59', '2010:AgeGroup13:60-64',
       '2010:AgeGroup14:65-69', '2010:AgeGroup15:70-74',
       '2010:AgeGroup16:75-79', '2010:AgeGroup17:80-84',
       '2010:AgeGroup18:85+'],
      dtype='object')

In [171]:
first_pass_final.to_csv('../data/Census_2010_rates_1.csv')

In [175]:
first_pass_final[first_pass_final["fips"] == 2201]

,STNAME,CTYNAME,fips,AGEGRP,TOT_POP,pct_male,2010:AgeGroup01:0-4,2010:AgeGroup02:5-9,2010:AgeGroup03:10-14,2010:AgeGroup04:15-19,...,2010:AgeGroup09:40-44,2010:AgeGroup10:45-49,2010:AgeGroup11:50-54,2010:AgeGroup12:55-59,2010:AgeGroup13:60-64,2010:AgeGroup14:65-69,2010:AgeGroup15:70-74,2010:AgeGroup16:75-79,2010:AgeGroup17:80-84,2010:AgeGroup18:85+
16720,Alaska,Prince of Wales-Hyder Census Area,2201,0,5559,0.552258,0.070262,0.063169,0.06148,0.063056,...,0.063169,0.073077,0.088616,0.07837,0.057651,0.035919,0.028938,0.018579,0.014638,0.015426

In [ ]:
first_pass_final[first_pass_final["CTYNAME"].str.contains('Buena Vista')]